### ISSUE TITLE
Updating Plugin

### ISSUE THREAD

**Issue by duplaja** [DaWoody/Astronomy-Picture-Of-the-Day#2]
Hello!

I was wondering if you had any plans on updating this plugin a bit? I can see a few tweaks that might make it a bit more efficient. If not, I planned on spinning up my own version, for some learning, but wanted to drop you a line first at least.

1) Instead of pulling with JS, pull with wp_remote_get, and store as a transient (reduces to a set number of calls, even if you call every 2 hours or so, rather than once per visitor).

2) In addition to the shortcode, also build APOD as as drop-in Gutenberg Block.

I'll probably go forward with this for my own learning / experience, but wanted to drop you a line. Feel free to shoot me a message if you'd like to collaborate!

Thanks!

**Comment by DaWoody** [comment]
Hi m8, thanks for the comment, have not at all been checking in here regularly as you may have noticed 😆. Have not really had plans of updating the plugin to be honest, good suggestions though for some improvements 😃! Did you go forward and create your own plugin btw ? Have a good one, cheers!

**Comment by duplaja** [comment]
Hey, no worries! I did go ahead and create my own version of it... but then promptly left it to stagnate, so I haven't even tested it recently. 

https://github.com/duplaja/Astronomy-Picture-of-the-Day-Revised

**Comment by DaWoody** [comment]
Cool man 😄! Glad you got to toy around yourself and made your own version! Yea I guess when I initially started it was also most because of having something fun to test around with, always good to have some kind of idea when learning and creating in general I think. Anyways thanks for the conversation, have a nice year! 😎
